ubuntu_trusty:
  image_id: ami-29ebb519
  key_name: ubuntu_trusty
  instance_type: t2.medium
  security_group_ids:
    - sg-89eedbec

angular:
  image_id: ami-29ebb519
  key_name: angular
  instance_type: t2.small
  security_group_ids:
    - sg-89eedbec


docker:
  image_id: ami-29ebb519
  key_name: docker
  instance_type: t2.small
  security_group_ids:
    - sg-89eedbec
