apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: flower
  name: flower-service
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: taskQueue
    component: flower
  publicIPs:
  - 192.168.33.10
